# this matches what the installer uses to create the admin.kubeconfig.  We must always honor this as a client or the admin.kubeconfig will become invalid
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-kubeconfig-client-ca
  namespace: openshift-config
  annotations:
    "openshift.io/owning-component": "kube-apiserver"
    "certificates.openshift.io/auto-regenerate-after-offline-expiry": "https://github.com/openshift/cluster-kube-apiserver-operator/pull/1757, '[sig-apps] Deployment RollingUpdateDeployment should delete old pods and create new ones [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]'"
data:
  ca-bundle.crt: |
    {{ .Assets | load "admin-kubeconfig-ca-bundle.crt" | indent 4 }}
